<link rel="stylesheet" href="css/play.css">

<div class="container">

    <nav class="play_nav">
        <ul class="normal-list fl-jc-b">
            <li><a class="normal-link c-black" href="">Mes Likes</a></li>            
            <li><a class="normal-link c-black" href="">Jouer</a></li>
            <li><a class="normal-link c-black" href="">Messages</a></li>
        </ul>
    </nav>

    <div id="for_about">
        <div id="before_card">
            
        </div>

        <div id="card" class="play_space_card fl-jc-a">
        </div>

        <div id="after_card">
            
        </div>
    </div>
</div>
<script src="js/class/match.class.js"></script>
<script src="js/main.js"></script>