<form action="register.php" method="POST">
    <label>Prenom</label>
    <input type="text" name="firstName">

    <label>Nom</label>
    <input type="text" name="lastName">

    <label>Email</label>
    <input type="email" name="email">

    <label>Mot de passe</label>
    <input type="password" name="password">

    <label>Age</label>
    <input type="text" name="age">

    <label>Description</label>
    <textarea name="desc"></textarea>


    <p>Genre</p>
    <label>Homme</label>
    <input type="radio" id="radio1" name="radio" value="H">

    <label>femme</label>
    <input type="radio" id="radio2" name="radio" value="F">

    <button type="submit">Envoyer</button>
</form>